"""
Ledger Normalizer - Sprint 37
Converts a ScientificLedger into Zenodo-compatible metadata.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from observer.scientific_ledger import ScientificLedger


def _dedupe_contributors(ledger: ScientificLedger) -> List[Dict]:
    seen = set()
    out = []
    for c in ledger.contributors:
        key = (c.name or "").strip().lower()
        if not key or key in seen:
            continue
        seen.add(key)
        d: Dict = {"name": c.name.strip()}
        if getattr(c, "orcid", None):
            d["orcid"] = c.orcid
        if getattr(c, "affiliation", None):
            d["affiliation"] = c.affiliation
        out.append(d)
    return out[:100]


def _collect_keywords(ledger: ScientificLedger) -> List[str]:
    seen = set()
    out = []
    for ws in ledger.workstreams:
        for s in ws.signals:
            k = s.strip().lower()
            if k and k not in seen:
                seen.add(k)
                out.append(s.strip())
            if len(out) >= 20:
                return out
    return out


def _collect_related_identifiers(ledger: ScientificLedger) -> List[Dict]:
    rels: List[Dict] = []
    seen = set()
    for art in ledger.artifacts:
        doi = art.get("doi")
        if doi and doi not in seen:
            seen.add(doi)
            rels.append({"identifier": doi, "relation": "isVersionOf"})
        gh = art.get("github_repo")
        if gh and gh not in seen:
            seen.add(gh)
            rels.append({"identifier": gh, "relation": "isSupplementTo"})
    return rels


def build_description(ledger: ScientificLedger) -> str:
    parts: List[str] = []
    if ledger.description:
        parts.append(ledger.description)
    if ledger.comprehension_summary:
        parts.append("")
        parts.append(ledger.comprehension_summary)
    parts.append("")
    parts.append(f"Generated by CoResearcher at {ledger.generated_at}.")
    parts.append(f"Ledger contains {len(ledger.artifacts)} artifacts and "
                 f"{len(ledger.workstreams)} workstreams.")
    return "\n".join(parts)


def normalize_for_zenodo(ledger: ScientificLedger) -> Dict:
    if not ledger.name:
        raise ValueError("ledger.name is required for Zenodo title")

    title = ledger.name
    description = build_description(ledger)
    creators = _dedupe_contributors(ledger)
    keywords = _collect_keywords(ledger)
    related = _collect_related_identifiers(ledger)

    notes_parts = [
        f"ledger_id={ledger.ledger_id}",
        f"artifacts={len(ledger.artifacts)}",
        f"workstreams={len(ledger.workstreams)}",
        f"scientific_unit={ledger.scientific_unit}",
    ]
    if getattr(ledger, "unit_rationale", None):
        notes_parts.append(f"unit_rationale={ledger.unit_rationale}")
    tl = ledger.timeline or {}
    if isinstance(tl, dict):
        start_year = tl.get("start_year")
        if start_year:
            notes_parts.append(f"start_year={start_year}")

    keywords_extended = list(keywords)
    unit = getattr(ledger, "scientific_unit", None)
    if unit and unit not in keywords_extended:
        keywords_extended.append(unit)

    metadata: Dict = {
        "title": title,
        "description": description,
        "creators": creators,
        "keywords": keywords_extended[:20],
        "related_identifiers": related,
        "notes": " | ".join(notes_parts),
        "upload_type": "dataset",
        "publication_date": str(ledger.generated_at)[:10] if ledger.generated_at else None,
        "language": "eng",
    }

    metadata = {k: v for k, v in metadata.items() if v is not None}

    return {"metadata": metadata}