"""
Sprint 37 Validation Script
Validates Zenodo publishing of ScientificLedger.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from typing import Optional

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from observer.scientific_ledger import ScientificLedger, LedgerWorkstream, LedgerContributor
from observer.ledger_generator import build_ledger
from observer.ledger_normalizer import normalize_for_zenodo, build_description
from observer.zenodo_publisher import ZenodoPublisher


class ValidationResult:
    def __init__(self) -> None:
        self.passed: list[str] = []
        self.failed: list[str] = []
        self.skipped: list[str] = []
        self.details: list[str] = []

    def add_pass(self, name: str, detail: str = "") -> None:
        self.passed.append(name)
        if detail:
            self.details.append(f"[PASS] {name}: {detail}")

    def add_fail(self, name: str, detail: str = "") -> None:
        self.failed.append(name)
        if detail:
            self.details.append(f"[FAIL] {name}: {detail}")

    def add_skip(self, name: str, reason: str) -> None:
        self.skipped.append(name)
        self.details.append(f"[SKIP] {name}: {reason}")

    def summary(self) -> str:
        lines = [
            "=== Sprint 37 Validation ===",
            f"PASSED : {len(self.passed)}",
            f"FAILED : {len(self.failed)}",
            f"SKIPPED: {len(self.skipped)}",
        ]
        if self.details:
            lines.append("")
            lines.extend(self.details)
        return "\n".join(lines)


def _build_sample_ledger() -> ScientificLedger:
    """Build a minimal ledger from synthetic artifacts for testing."""
    from observer.scientific_artifact import ScientificArtifact, Contributor

    artifacts = [
        ScientificArtifact(
            artifact_id="zenodo:10.5281/zenodo.1234567",
            type="dataset",
            doi="10.5281/zenodo.1234567",
            title="Sample EEG Dataset",
            contributors=[Contributor(name="Alice Example", orcid="0000-0001-2345-6789")],
            created_at="2025-01-15",
            evidence_sources=["zenodo"],
        ),
        ScientificArtifact(
            artifact_id="github:example/project:latest",
            type="software_release",
            title="Example Analysis Tool",
            github_repo="https://github.com/example/project",
            github_release="v1.0.0",
            contributors=[Contributor(name="Bob Builder", github="bob")],
            created_at="2025-03-01",
            evidence_sources=["github"],
        ),
        ScientificArtifact(
            artifact_id="openalex:W123456789",
            type="paper",
            doi="10.1234/example.2025.001",
            title="A Demo Paper on Something",
            contributors=[Contributor(name="Alice Example")],
            created_at="2025-02-10",
            evidence_sources=["openalex"],
        ),
    ]

    ledger = build_ledger(
        artifacts=artifacts,
        ledger_id="sprint37-test-ledger",
        name="Sprint 37 Validation Ledger",
        description="A synthetic ledger for validating Zenodo publishing.",
    )
    return ledger


def test_normalizer_contract(result: ValidationResult) -> None:
    """Test that the normalizer produces a valid Zenodo metadata dict."""
    try:
        ledger = _build_sample_ledger()
        payload = normalize_for_zenodo(ledger)

        assert isinstance(payload, dict), "normalize_for_zenodo must return a dict"
        assert "metadata" in payload, "payload must contain 'metadata'"
        meta = payload["metadata"]

        assert meta.get("title") == ledger.name, "title must match ledger.name"
        assert meta.get("upload_type") == "dataset", "upload_type must be 'dataset'"
        assert isinstance(meta.get("creators"), list), "creators must be a list"

        desc = meta.get("description", "")
        assert "Generated by CoResearcher" in desc, "description must contain generation note"

        assert isinstance(meta.get("keywords"), list), "keywords must be a list"

        # semantic layer checks
        assert meta.get("notes", "").count("scientific_unit=") == 1, \
            "notes must include scientific_unit"
        assert "investigatable_claim" in meta.get("notes", ""), \
            "notes must include the default scientific_unit value"
        assert "investigatable_claim" in meta.get("keywords", []), \
            "keywords must include scientific_unit"

        result.add_pass("normalizer_contract", json.dumps(payload, indent=2)[:200] + "...")
    except Exception as e:
        result.add_fail("normalizer_contract", str(e))


def test_publisher_sandbox_dry_run(result: ValidationResult) -> None:
    """Test deposit creation in sandbox without publishing (no DOI)."""
    token = os.environ.get("ZENODO_TOKEN")
    if not token:
        result.add_skip("publisher_sandbox_dry_run", "ZENODO_TOKEN not set in environment")
        return

    try:
        ledger = _build_sample_ledger()
        publisher = ZenodoPublisher(api_token=token, use_sandbox=True)
        deposition = publisher.deposit(ledger, publish=False)

        assert deposition.get("id"), "deposition must have an 'id'"
        status = deposition.get("status", "")
        assert status in ("draft", "inprogress", "unsubmitted"), f"unexpected status: {status}"

        result.add_pass("publisher_sandbox_dry_run", f"deposition_id={deposition['id']}, status={status}")
    except Exception as e:
        result.add_fail("publisher_sandbox_dry_run", str(e))


def test_publisher_sandbox_publish(result: ValidationResult) -> None:
    """Test full publish flow in sandbox and verify DOI is returned."""
    token = os.environ.get("ZENODO_TOKEN")
    if not token:
        result.add_skip("publisher_sandbox_publish", "ZENODO_TOKEN not set in environment")
        return

    try:
        ledger = _build_sample_ledger()
        publisher = ZenodoPublisher(api_token=token, use_sandbox=True)
        doi = publisher.publish_and_get_doi(ledger)

        assert doi.startswith("10.5281/zenodo."), f"invalid DOI format: {doi}"

        result.add_pass("publisher_sandbox_publish", f"DOI={doi}")
    except Exception as e:
        result.add_fail("publisher_sandbox_publish", str(e))


def test_description_builder(result: ValidationResult) -> None:
    """Test description builder handles empty and populated ledgers."""
    try:
        ledger = _build_sample_ledger()
        desc = build_description(ledger)
        assert "Generated by CoResearcher" in desc
        assert str(len(ledger.artifacts)) in desc

        empty_ledger = ScientificLedger(ledger_id="empty", name="Empty")
        empty_desc = build_description(empty_ledger)
        assert isinstance(empty_desc, str)

        result.add_pass("description_builder", "description contains expected fields")
    except Exception as e:
        result.add_fail("description_builder", str(e))


def test_unit_semantics_defaults(result: ValidationResult) -> None:
    """Test that a ledger without explicit unit_rationale still propagates scientific_unit."""
    try:
        ledger = ScientificLedger(
            ledger_id="sem-test",
            name="Semantics Test",
            description="Test semantics",
        )
        assert ledger.scientific_unit == "investigatable_claim"
        assert ledger.unit_rationale == ""

        payload = normalize_for_zenodo(ledger)
        notes = payload["metadata"].get("notes", "")
        assert "scientific_unit=investigatable_claim" in notes
        assert "unit_rationale=" not in notes

        result.add_pass("unit_semantics_defaults",
                        "defaults propagate correctly without explicit rationale")
    except Exception as e:
        result.add_fail("unit_semantics_defaults", str(e))


def test_unit_semantics_explicit(result: ValidationResult) -> None:
    """Test that explicit unit_rationale is included in notes."""
    try:
        ledger = ScientificLedger(
            ledger_id="sem-explicit",
            name="Semantics Explicit",
            description="Test",
            scientific_unit="experimental_comparison",
            unit_rationale="compares baseline vs treated",
        )
        payload = normalize_for_zenodo(ledger)
        notes = payload["metadata"].get("notes", "")
        assert "scientific_unit=experimental_comparison" in notes
        assert "unit_rationale=compares baseline vs treated" in notes
        assert "experimental_comparison" in payload["metadata"].get("keywords", [])

        result.add_pass("unit_semantics_explicit",
                        "explicit semantics propagate to notes and keywords")
    except Exception as e:
        result.add_fail("unit_semantics_explicit", str(e))


def main() -> int:
    result = ValidationResult()

    # Unit tests (no token required)
    test_normalizer_contract(result)
    test_description_builder(result)
    test_unit_semantics_defaults(result)
    test_unit_semantics_explicit(result)

    # Integration tests (require ZENODO_TOKEN)
    if os.environ.get("ZENODO_TOKEN"):
        print("ZENODO_TOKEN detected. Running sandbox publish tests.")
        test_publisher_sandbox_dry_run(result)
        test_publisher_sandbox_publish(result)
    else:
        print("ZENODO_TOKEN not set. Skipping live Zenodo tests.")
        result.add_skip("live_zenodo_tests", "ZENODO_TOKEN not set")

    print(result.summary())

    if result.failed:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())